config/routes.rb
Reactivewebsiteexample::Application.routes.draw do

  ActiveAdmin.routes(self)
  devise_for :admin_users, ActiveAdmin::Devise.config

  devise_for :users

  match '/sidebar_tiles'  => 'application#sidebar_tiles', as: :sidebar_tiles

  resources :dependencies,  only: %w(index)
  resources :projects,      only: %w(index show)
  resources :branches,      only: %w(index show)
  resources :builds,        only: %w(index show)
  resources :steps,         only: %w(index show)
  resources :actions,       only: %w(index show)

  root :to => 'pages#home'
  match '/home'   => 'pages#home',  as: :home
  match '/about'  => 'pages#about', as: :about
  match '/management'  => 'pages#management', as: :management
end

app/models/build.rb
class Build < ActiveRecord::Base
  attr_accessible :finished_at, :started_at, :status

  validates_presence_of :commit
  validates_presence_of :branch

  belongs_to :commit
  belongs_to :branch
  has_many :steps

  # Returns a list of {id => <id>, value => <value>}
  def self.summary(branch_id)

    query = joins(:commit)
           .select('builds.*, commits.digest')
           .where('builds.branch_id = ?', branch_id)

    strftime = lambda { |d| d.strftime('%Y.%m.%d-%H:%M:%S') }
    query.inject([]) do |memo, build|
      memo << {:id => build.id, :value => [
        strftime.(build.started_at),
        strftime.(build.finished_at),
        build.digest[0..14]
      ]}
    end # return
  end

  # Builds listing with commit (optionally for a particular branch)
  def self.listing(branch_id = nil)
    builds = self.order('finished_at desc')
    unless branch_id.nil? # builds for the branch with the id 'branch_id'
      builds = builds.where('branch_id = ?', branch_id)
    end
    builds = builds.joins(:commit).select('builds.*, '\
      'commits.digest as commit_digest, '\
      'commits.url as commit_url, '\
      'commits.timestamp as commit_timestamp'
    ) # return
  end

end

app/controllers/builds_controller.rb
class BuildsController < ApplicationController

  def index
    respond_to do |format|

      format.html do
        page_n = params[:page]

        @builds = if params[:id].nil?
          Build.listing().page(page_n).per(Settings.builds.listing.pages)
        else
          Build.listing(params[:id])
              .page(page_n).per(Settings.branches.builds.listing.pages)
        end

        if request.xhr? == 0 # request is ajax
          case params[:selector].to_sym
          when :listing
            locals = {builds: @builds}
            if params[:id]
              locals[:id] = params[:id]
            end
            render partial: 'builds/listing', locals: locals
          end
        end

      end

      format.json do
        case params[:selector].to_sym
        when :summary
          render(json: Build.summary(params[:id]))
        end
      end

    end
  end

  def show
    @build = Build.joins(:commit)
        .select('builds.*, commits.digest as commit_digest, '\
                'commits.url as commit_url, '\
                'commits.timestamp as commit_timestamp')
        .find(params[:id])

    respond_to do |format|
      format.html do
        if request.xhr? != 0 # request isn't ajax
          # ==> RESOURCES SELECTORS SETUP
          @resources_avail = :steps, :actions
          gon.current_resource = {
            id: @build.id,
            type: :builds
          }
        end

        render layout: (request.xhr? != 0)
      end
    end
  end
end

app/helpers/builds_helper.rb
module BuildsHelper
end

app/views/builds/_listing.html.haml
%table#builds-listing.table.table-striped.table-condensed.table-bordered
  %thead
    %tr
      %th Started at
      %th Finished at
      %th Status
      %th Commit digest
      %th Commit URL
      %th Commit Timestamp
  %tbody
    - builds.each do |build|
      %tr
        %td= opt_elem !build.started_at.nil?, link_to(build.started_at.strftime('%Y-%m-%d %H:%M:%S'), build_path(build)), 'Not started yet.'
        %td= opt_elem !build.started_at.nil?, link_to(build.finished_at.strftime('%Y-%m-%d %H:%M:%S'), build_path(build)), 'Not finished yet.'
        %td= opt_elem !build.status.blank?, link_to(build.status, build_path(build))
        %td= build.commit_url.blank? ? build.commit_digest : link_to(build.commit_digest, build.commit_url)
        %td= opt_elem !build.commit_url.blank?, link_to(build.commit_url, build.commit_url)
        %td= build.commit_url.blank? ? build.commit_timestamp : link_to(build.commit_timestamp, build.commit_url)

- params = {controller: 'builds', action: 'index', selector: 'listing'}
- params[:id] = branch_id if defined?(branch_id)
= paginate builds, remote: true, params: params

app/views/builds/index.html.haml
%h2 Builds

#builds.well

  -# Listing for all builds
  %h3 Builds Listing
  #builds-listing-wrp= render partial: 'builds/listing', locals: {builds: @builds}


-# { Assets
-# Enable gon for ajax requests
- if ajax?
  = include_gon
- unless ajax?
  - content_for :stylesheets do
    = stylesheet_link_tag :'builds/index', :media => 'all'
  - content_for :javascripts do
    = javascript_include_tag :'builds/index'
-# }

app/views/builds/show.html.haml
- title = (@build.started_at.blank? || @build.finished_at.blank?) ? "Build ##{@build.id}" : "Build: from #{@build.started_at} to #{@build.finished_at}"
- if ajax?
  %h3#build-title.res-title= title
- else
  %h2#build-title.res-title= title
  // resource selectors, used to select a particular resource
  = render 'resource_selectors'

#build.res-view{class: "#{'well' unless ajax?}"}
  -# Build informations
  %dl#build-infos-wrp.row-fluid
    %dt#build-status-lbl Status
    %dd#build-status= opt_elem !@build.status.blank?, @build.status
    %dt#build-startedat-lbl Started At
    %dd#build-startedat= opt_elem !@build.started_at.blank?, @build.started_at, 'Not started yet.'
    %dt#build-finishedat-lbl Finished At
    %dd#build-finishedat= opt_elem !@build.finished_at.blank?, @build.finished_at, 'Not finished yet.'
    %dt#build-commit-infos-lbl Commit
    %dd#build-commit-infos-wrp
      %dl#build-commit-infos-wrp.row-fluid
        %dt#build-commit-digest-lbl Commit Digest
        %dd#build-commit-digest= @build.commit_digest
        %dt#build-commit-url-lbl Commit URL
        %dd#build-commit-url= opt_elem !@build.commit_url.blank?, link_to(@build.commit_url, @build.commit_url)
        %dt#build-commit-timestamp-lbl Commit Timestamp
        %dd#build-commit-timestamp= @build.commit_timestamp


-# { Assets
-# Enable gon for ajax requests
- if ajax?
  = include_gon
- unless ajax?
  - content_for :stylesheets do
    = stylesheet_link_tag :'builds/show', :media => 'all'
  - content_for :javascripts do
    = javascript_include_tag :'builds/show'
-# }